server:
  port: 8060
spring:
  application:
    name: users
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/vacations
    username: vacations
    password: 123456
  aop:
    proxy-target-class: true

config:
  oauth2:
    privateKey: verysecret